### ISSUE TITLE
SQL error on player login

### ISSUE THREAD

**Issue by Darkilen** [pavog/craftconomy3#60]
Hello,
One of our player just log in and CraftConomy3 started spam our console at each tick with an SQL error (https://pastebin.com/NGrU8A1z). We had to remove his entry in MySQL in order to stop the spam.

What can we do to prevent further error like this one ?

Spec: 

- CraftConomy3 v3.5.2
- Minecraft 1.14.4
- Paperspigot

Thanks

**Comment by pavog** [comment]
Hi Darkilen,
thanks for reporting this issue.

It seems like there are / were more than one records in the account table with the same playername.
I don't know how this can happen since the playername should be an unique key.

Can you check if this is / was the problem?

Thanks

**Comment by Darkilen** [comment]
Hello,

We only have/had one record for this account (currently, 2 players had this issue)

Thanks

**Comment by pavog** [comment]
Mhh that's weird.

I have to dig deeper into this. I don't think that you can do anything to prevent this issue.


**Note to my self:**
The sql error says `Subquery returns more than 1 row`. The query is in this [file](https://github.com/pavog/craftconomy3/blob/master/src/main/java/com/greatmancode/craftconomy3/storage/sql/tables/BalanceTable.java#L70). 
```
"SELECT balance, worldName, currency_id, username_id FROM " + getPrefix() + TABLE_NAME + " " +
"LEFT JOIN " + getPrefix() + CurrencyTable.TABLE_NAME + " " +
"ON " + getPrefix() + TABLE_NAME + ".currency_id = " + getPrefix() + CurrencyTable.TABLE_NAME + ".name " +
"WHERE " + getPrefix() + TABLE_NAME + ".username_id = (" + AccountTable.sqlAccountIDbyName(getPrefix()) + ") " +
"AND " + WORLD_NAME_FIELD + "=? AND " + getPrefix() + CurrencyTable.TABLE_NAME + ".name=?";
```

And since the error mentions a subquery I guess it's this part:
`"WHERE " + getPrefix() + TABLE_NAME + ".username_id = (" + ccountTable.sqlAccountIDbyName(getPrefix()) + ") " +`

The code searches for the account id by name and is located [here](https://github.com/pavog/craftconomy3/blob/master/src/main/java/com/greatmancode/craftconomy3/storage/sql/tables/AccountTable.java#L85).

Like the name suggests it returns the sql to get the account id by name:
`SELECT id FROM " + prefix + AccountTable.TABLE_NAME + " WHERE name =?`

**Comment by Darkilen** [comment]
Resolved in https://github.com/pavog/craftconomy3/releases/tag/3.5.4 (maybe before)
