### ISSUE TITLE
README.md issue

### ISSUE THREAD

**Issue by cyb3rm4n** [pavog/craftconomy3#77]
Just tested plugin to work on 1.7.10 (author wrote that his 3.3.1 version works in 1.7,9)
PLugin works fine. No loading errors on start, ccsetup command and on stop o the server.
Here's log: https://paste.dimdev.org/quvicasiju.md

**Comment by pavog** [comment]
I'm sorry if I misunderstood this but you mean the issue is that the readme only says "Bukkit/Spigot 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14 supported" and it works on 1.7 too?

If so: I can also add a note, like "older mc versions might work too".
But: This project can only be compiled (and unit tested) for the listed versions, as versions older than 1.8 do not exist in the [maven repository for Spigot](https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/). 
This project uses [TravisCI](https://travis-ci.org/github/pavog/craftconomy3) to automate the execution of unit tests that depend on the existing Spigot versions from its maven repository. That means that I cannot guarantee that older versions will work.

**Comment by cyb3rm4n** [comment]
that would be good.

**Comment by pavog** [comment]
I added a note to the readme.
Thank you for your contribution.
